services:
  comfyui-worker:
    image: howardwkim/runpod-worker-comfy-latent-space:howard-custom-base-1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - SERVE_API_LOCALLY=true
    ports:
      - "8000:8000"
      - "8188:8188"
    volumes:
      - latentspace:/workspace
      - ./data/comfyui/output:/comfyui/output
      - ./data/runpod-volume:/runpod-volume
